# Overview {.unnumbered}

Making an R package develops generic coding skills and gives you valuable insight to how R works. We’ll cover setting up a package project, creating functions, documenting them with roxygen, creating vignettes, unit testing, package testing, version control with git, and distribution with github.

You will need only very basic R skills and a willingness to learn. The only people this would not be suitable for are those with zero previous experience in R (unless you know you pick up coding languages quickly). If you can install packages and have written an analysis script, you'll be fine.

<!--
::: {.callout-important}
## Register for free at EventBrite
[Register](https://coding-club-packages.eventbrite.co.uk) to help us keep organised and let us know a little bit about your experience. Space is unlimited, so don't worry if you can't make all of the dates. We'll record the sessions and make them public ASAP so you can catch up if you miss the live session.
:::
-->

## Demo Package

This book contains all of the instructions to create your first R package. But if you fall behind and need to download the most recent version of the demopkg, visit <https://github.com/psyteachr/demopkg> and check the README for download instructions. 

## Schedule

This originally ran as a weekly online workshop in 2022 for the [PsyTeachR](https://psyteachr.github.io) Coding Club at the University of Glasgow School of Psychology & Neuroscience. The passcode for all recordings is `codingclub22!`

1. Setting up a package project (2022-10-05) [Recording](https://uofglasgow.zoom.us/rec/share/mxeupKeSgQ7ZekH86RV1UQ-4ROAv6xQoJRB7G2Z7lnLovcTGdVVs39mRb1q7cvZn.UYy6h6E6Sc6xOCOr)

    Create a package project and edit the default files. Well start using the most helpful package, usethis.

2. Adding Data (2022-10-12) [Recording](https://uofglasgow.zoom.us/rec/share/o0RHg82nSsyPLSMpA5hxHdqiHnc86H7zmBvzDL-n6ICqq0NQ1wHf8FKF3zvkeGmj.H72yZQDGbVST5gqQ)

    Add datasets to your package and document them with a codebook. You can use our demo data or your own.

3. Custom Functions (2022-10-19) [Recording](https://uofglasgow.zoom.us/rec/share/GsdzG_rdN-ifbRqRndm-lUKXYNqf8dQB12tnkJwmWD2Z8Po4koqArTcHFtH-DXlx.QLwfu5cwMgQ3OCK3)

    Learn to write custom functions and include them in your package.

4. Documentation (2022-10-26) [Recording](https://uofglasgow.zoom.us/rec/share/sOMxVB9wd084RpyVbz_HyFh1tTLP3PqmQVMBBONNc4SucxDYp8u4XSlujlnj7ZW4.egNs8uuVGd1Al5oR)

    Write function documentation using the roxygen format. This is what creates the help documentation for functions.
    
5. Unit Tests (2022-11-02) [Recording](https://uofglasgow.zoom.us/rec/share/F--AV75X9YORfesOFy3-RXFRhoqinE6BVpxcKKj8LJYkMPHdAzR-6mxYRdzsKp8d.eb_tjAl-_A29Ur8P)

    Write unit tests for your custom functions using testthat.

6. Vignettes (2022-11-09) [Recording](https://uofglasgow.zoom.us/rec/share/GkpP8Q473G517qIObour0HjqfylSRMNmcv1EEMOMUM56xXN_fnZQg2OatYPOWx7V.U_7Gy0scEJCNS6bv)

    Include your study analysis code as a package vignette.

7. Pkgdown Websites (2022-11-16) [Recording](https://uofglasgow.zoom.us/rec/share/bRqwxQOd7rNw3ie7xwIx7Oj1le7XoxClIIMWt00-unBzcKe9enVeSSeh9O3B_9l7.0KvcITpFNTLrDghJ)

    Create a package website using pkgdown.

8. Package Maintenance (2022-11-23) [Recording](https://uofglasgow.zoom.us/rec/share/IIjuf9y7xF4t_KuLK_i324CMp3fu71hAnONq93lQr9_d-Ye9leOy7TCrI4VId9TV.jAqwDHjtQir5UpLx)

    How to run CMD-check to make sure everything is put together right, and how to troubleshoot the inevitable problems.
    
::: {.callout-important}
## No session 2022-11-30
The UK University and College Union (UCU) is [planning industrial action](https://www.ucu.org.uk/article/12609/Biggest-ever-university-strikes-set-to-hit-UK-campuses-over-pay-conditions--pensions) on 2022-11-30, and Lisa is a union member, so this session will be delayed until 12-07, unless the universities propose a reasonable offer.
:::

9. Sharing your package (2022-12-07)

    Set up a github account and make a package repository to share your package and pkgdown website.
    
## Resources

* [R Packages](https://r-pkgs.org/) @r-packages
* [R package primer](https://kbroman.org/pkg_primer/) by Karl Broman
* [usethis](https://usethis.r-lib.org/)
* [testthat](https://testthat.r-lib.org/)
* [pkgdown](https://pkgdown.r-lib.org/)
* [vertical](https://crumplab.com/vertical/)
